drop database if exists TECH; 

create database TECH;

use TECH;

CREATE TABLE USERINFO (
ADMINID varchar(255) not NULL, 
USERID varchar(255) not NULL,
EMAIL varchar(255) not NULL, 
PASS varchar(255) not NULL,
USERNAME varchar(255) not NULL,
USERLOC varchar(255) not NULL, 
PRIMARY KEY (USERID)
); 

CREATE TABLE DEVICES (
DEVID int not NULL, 
DEVNAME varchar(255) not NULL,
DEVTYPE varchar(255) not NULL, 
DEVLOC varchar(255) not NULL,   
PRIMARY KEY (DEVID)
); 

CREATE TABLE USERDEVICE (
DEVID int NOT NULL, 
USERID varchar(255) NOT NULL, 
constraint USERDEVICE_PK PRIMARY KEY (USERID, DEVID),
FOREIGN KEY DEV_FK01(DEVID) REFERENCES DEVICES(DEVID),
FOREIGN KEY USER_FK02(USERID) REFERENCES USERINFO(USERID)
);

CREATE Table ENVIRLAYOUT (
BEACID varchar(255) not NULL,
ALIAS varchar(255) not NULL, 
LOCTYPE varchar(255) not NULL, 
DEVSINRANG enum('t', 'u', 'v', 'w', 'x', 'y', 'z'),
PRIMARY KEY (BEACID)
); 

CREATE Table TIMEDEVICE (
BEACID varchar(255) not NULL,
DEVID int NOT NULL,
constraint BEAC_PK PRIMARY KEY (BEACID, DEVID),
FOREIGN KEY BEAC_FK01(BEACID) REFERENCES ENVIRLAYOUT(BEACID),
FOREIGN KEY DEV_FK02(DEVID) REFERENCES DEVICES(DEVID),
STARTTIME timestamp NOT NULL,
ENDTIME timestamp
);
